#!/bin/bash

kubectl create -f pv_minikube_internal.yaml
kubectl create -f pvc-galaxy.yaml
kubectl get pv
kubectl get pvc

kubectl create -f galaxy-k8s-service.yaml
#kubectl create -f galaxy-k8s-rc-user.yaml
kubectl create -f galaxy-k8s-rc-dev.yaml
ip=$(kubectl cluster-info | grep 'Kubernetes master' | sed 's!^.*https://\(.*\):.*$!\1!')
port=$(kubectl describe svc/galaxy-svc-k8s | grep ^NodePort | sed 's!^.*[[:space:]]\([[:digit:]]*\)/.*$!\1!')
echo Galaxy is available at \"http://$ip:$port\".
