#!/bin/bash

# First, install minikube if not already done:
if ! which -s /usr/local/bin/minikube ; then
	curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.15.0/minikube-darwin-amd64 # ! Check for newer version of minikube, see https://github.com/kubernetes/minikube/releases
	chmod +x minikube
	mv minikube /usr/local/bin/
fi

# Then, start minikube:
minikube_stopped=$(minikube status | grep '\(Stopped\|Does\ Not\ Exist\)')
if [ -n "$minikube_stopped" ] ; then
	minikube start --memory 4096
fi

# Open minikube dashboard
kubectl config use-context minikube
kubectl get pods --all-namespaces
minikube dashboard

kubectl create -f pv_minikube_internal.yaml
kubectl create -f pvc-galaxy.yaml
kubectl get pv
kubectl get pvc

kubectl delete pods,services --all
kubectl create -f galaxy-k8s-service.yaml
#kubectl create -f galaxy-k8s-rc-user.yaml
#kubectl create -f galaxy-k8s-rc.yaml
#kubectl create -f https://raw.githubusercontent.com/phnmnl/docker-galaxy-k8s-runtime/master/deployment/galaxy_rc.yaml
kubectl create -f galaxy-k8s-rc-dev.yaml
ip=$(kubectl cluster-info | grep 'Kubernetes master' | sed 's!^.*https://\(.*\):.*$!\1!')
port=$(kubectl describe svc/galaxy-svc-k8s | grep ^NodePort | sed 's!^.*[[:space:]]\([[:digit:]]*\)/.*$!\1!')
echo Galaxy is available at \"http://$ip:$port\".
