# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "w4m-planemo"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  
  config.vm.provision :shell, path: "bootstrap.sh"
  
end
