# -*- mode: ruby -*-
# vi: ft=ruby sw=0 ts=2 et fdm=marker

Vagrant.configure(2) do |config|

  restart_required = false
  
  # Box
#  config.vm.box = "ubuntu/trusty64"
  config.vm.box = "debian/jessie64"
  
  # VM name
  vm_name = "zebra"
  config.vm.hostname = vm_name
  config.vm.define vm_name
  
  # Set virtualbox parameters
  config.vm.provider :virtualbox do |vb|
    vb.name = vm_name
    vb.memory = "2048"
    vb.gui = false
  end

  # Network
  config.vm.network :forwarded_port, guest: 8080, host: 8080

  # Install private config (how?)
  # Check if keys/password are still present in my config and possibly make it public. Split config into mailcfg and devcfg.
  
  # Install Galaxy
  config.vm.provision :shell, privileged: true, inline: "apt-get install -y git make python-virtualenv"
  config.vm.provision :shell, privileged: false, inline: "git clone https://github.com/phnmnl/galaxy"
  config.vm.provision :shell, privileged: false, inline: "cd galaxy && virtualenv .venv"
  config.vm.provision :shell, privileged: false, inline: "cd galaxy && source .venv/bin/activate && pip install --upgrade setuptools"

end
