# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

  config.vm.box = "cmiles/gentoo-amd64-minimal"
  config.vm.hostname = "docker-tester"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end
  
  #config.vm.provision "docker"
  config.vm.provision :shell, path: "bootstrap.sh"
  
end
