# -*- mode: ruby -*-
# vi: ft=ruby ts=2 et

Vagrant.configure(2) do |config|

  # Box
  config.vm.box = "debian/jessie64"
  config.vm.hostname = "docker-tester"

  # Set virtual memory
#  config.vm.provider "virtualbox" do |vb|
#      vb.memory = "2048"
#  end
  
  config.vm.provision "docker"
  
end
